api_id: "${TG_API_ID}"
api_hash: "${TG_API_HASH}"
phone: "${TG_PHONE}"

session_file: "data/telegram.session"

chats:
  - -1001183585208
  - -1001832666352
  - -4678357599
  - -1002027203833
  - -1002355814838
  - -662388734
  - -1001837175292

output_jsonl: "data/telegram_messages.jsonl"
state_file: "data/telegram_state.json"
whatsapp_auth_dir: "data/whatsapp_auth"
whatsapp_chats: 
  - 77054002056-1497843542@g.us
  - 77475741057-1459990002@g.us
  - 77017147022-1533658386@g.us
  - 77778163613-1538136976@g.us
  - 77772115449-1530865049@g.us
  - 77017887225-1468855868@g.us
  - 77475572044-1567051602@g.us
  - 120363325328510648@g.us
  - 120363049216904693@g.us
  - 120363213432335386@g.us
  - 77775972299-1599058706@g.us
  - 77051846623-1632512784@g.us
  - 77017582652-1578307475@g.us
  - 77772579456-1534920227@g.us
  - 120363173746340495@g.us
  - 120363405427497192@g.us
  - 120363402636017276@g.us
  - 120363295814723721@g.us
  - 120363199590764686@g.us
  - 120363423687483006@g.us
  - 77029992700-1449816829@g.us  # Банкоматы_ мониторинг
  - 77010750100-1488538674@g.us  # МОНИТОРИНГ

whatsapp_output_jsonl: "data/telegram_messages.jsonl"
initial_days: 1
initial_limit: 0
